"""Priority employers by country (ISO names used in the student profile)."""

from __future__ import annotations

# name, extra aliases, mailbox domain, career hosts, greenhouse, lever, smartrecruiters
CountryRows = tuple[tuple[object, ...], ...]


def _rows(*items: tuple[object, ...]) -> CountryRows:
    return tuple(items)


COUNTRY_EMPLOYER_ROWS: dict[str, CountryRows] = {
    "Canada": _rows(
        ("Shopify", "", "shopify.com", "careers.shopify.com", "shopify", "", ""),
        ("Royal Bank of Canada", "rbc|rbc royal bank", "rbc.com", "jobs.rbc.com", "", "", ""),
        ("TD Bank", "td canada trust|toronto dominion", "td.com", "jobs.td.com", "", "", ""),
        ("Scotiabank", "bank of nova scotia|scotia bank", "scotiabank.com", "jobs.scotiabank.com", "", "", ""),
        ("Bank of Montreal", "bmo", "bmo.com", "jobs.bmo.com", "", "", ""),
        ("CIBC", "canadian imperial bank of commerce", "cibc.com", "cibc.com", "", "", ""),
        ("Bell Canada", "bell", "bell.ca", "jobs.bell.ca", "", "", ""),
        ("Rogers Communications", "rogers", "rogers.com", "jobs.rogers.com", "", "", ""),
        ("Telus", "telus communications", "telus.com", "jobs.telus.com", "", "", ""),
        ("Bombardier", "bombardier aviation", "bombardier.com", "bombardier.com", "", "", ""),
        ("Air Canada", "aircanada", "aircanada.com", "careers.aircanada.com", "", "", ""),
        ("WestJet", "west jet", "westjet.com", "westjet.com", "", "", ""),
        ("SNC-Lavalin", "snc lavalin|atkinsrealis|atkins realis", "atkinsrealis.com", "careers.atkinsrealis.com", "", "", ""),
        ("WSP Global", "wsp", "wsp.com", "careers.wsp.com", "", "", ""),
        ("Hatch", "hatch ltd", "hatch.com", "jobs.hatch.com", "", "", ""),
        ("Golder Associates", "golder", "golder.com", "golder.com", "", "", ""),
        ("Manulife", "manulife financial", "manulife.com", "jobs.manulife.com", "", "", ""),
        ("Sun Life Financial", "sun life", "sunlife.com", "jobs.sunlife.com", "", "", ""),
        ("Desjardins", "mouvement desjardins", "desjardins.com", "jobs.desjardins.com", "", "", ""),
        ("Hydro-Québec", "hydro quebec", "hydroquebec.com", "hydroquebec.com", "", "", ""),
        ("Fortis Inc", "fortis", "fortisinc.com", "fortisinc.com", "", "", ""),
        ("OpenText", "opentext", "opentext.com", "careers.opentext.com", "", "", ""),
        ("BlackBerry", "blackberry limited", "blackberry.com", "blackberry.com", "", "", ""),
        ("Magna International", "magna", "magna.com", "careers.magna.com", "", "", ""),
        ("CAE", "cae inc", "cae.com", "cae.com", "", "", ""),
        ("Canadian Tire", "canadian tire corporation", "canadiantire.ca", "careers.canadiantire.ca", "", "", ""),
        ("Sobeys", "sobeys inc", "sobeys.com", "careers.sobeys.com", "", "", ""),
        ("Metro Inc", "metro", "metro.ca", "metro.ca", "", "", ""),
        ("Loblaw Companies", "loblaw|loblaws", "loblaw.ca", "careers.loblaw.ca", "", "", ""),
        ("Hudson’s Bay Company", "hudsons bay|hbc|hudson's bay", "hbc.com", "hbc.com", "", "", ""),
        ("Couche-Tard", "alimentation couche-tard|circlek|circle k", "couchetard.com", "jobs.couchetard.com", "", "", ""),
        ("McCain Foods", "mccain", "mccain.com", "mccain.com", "", "", ""),
        ("Saputo", "saputo inc", "saputo.com", "saputo.com", "", "", ""),
        ("BCE Inc", "bce", "bce.ca", "bce.ca", "", "", ""),
        ("Enbridge", "enbridge inc", "enbridge.com", "careers.enbridge.com", "", "", ""),
        ("Suncor Energy", "suncor", "suncor.com", "suncor.com", "", "", ""),
        ("Irving Oil", "irving", "irvingoil.com", "irvingoil.com", "", "", ""),
        ("Cenovus Energy", "cenovus", "cenovus.com", "cenovus.com", "", "", ""),
        ("Petro-Canada", "petro canada", "petro-canada.ca", "petro-canada.ca", "", "", ""),
        ("Canadian Natural Resources", "cnrl|canadian natural", "cnrl.com", "cnrl.com", "", "", ""),
        ("Teck Resources", "teck", "teck.com", "careers.teck.com", "", "", ""),
        ("Barrick Gold", "barrick", "barrick.com", "careers.barrick.com", "", "", ""),
        ("Agnico Eagle Mines", "agnico eagle", "agnicoeagle.com", "careers.agnicoeagle.com", "", "", ""),
        ("Cameco", "", "cameco.com", "cameco.com", "", "", ""),
        ("Nutrien", "", "nutrien.com", "jobs.nutrien.com", "", "", ""),
        ("Canfor", "", "canfor.com", "canfor.com", "", "", ""),
        ("West Fraser Timber", "west fraser", "westfraser.com", "westfraser.com", "", "", ""),
        ("Resolute Forest Products", "resolute fp|resolute", "resolutefp.com", "resolutefp.com", "", "", ""),
        ("Kruger", "kruger inc", "kruger.com", "kruger.com", "", "", ""),
        ("Dollarama", "", "dollarama.com", "dollarama.com", "", "", ""),
        ("Aritzia", "", "aritzia.com", "aritzia.com", "", "", ""),
        ("Lululemon", "lululemon athletica", "lululemon.com", "careers.lululemon.com", "lululemon", "", ""),
        ("Canada Goose", "", "canadagoose.com", "canadagoose.com", "", "", ""),
        ("Roots", "roots canada", "roots.com", "roots.com", "", "", ""),
        ("Tim Hortons", "timhortons", "timhortons.com", "timhortons.com", "", "", ""),
        ("McDonald's Canada", "mcdonalds canada|mcdonald's", "mcdonalds.ca", "careers.mcdonalds.ca", "", "", ""),
        ("KFC Canada", "kfc", "kfc.ca", "kfc.ca", "", "", ""),
        ("Starbucks Canada", "starbucks", "starbucks.ca", "starbucks.com", "", "", ""),
        ("Amazon Canada", "amazon.ca|amazon", "amazon.com", "amazon.jobs", "", "", ""),
        ("Google Canada", "google", "google.com", "careers.google.com", "", "", ""),
        ("Microsoft Canada", "microsoft", "microsoft.com", "careers.microsoft.com", "", "", ""),
        ("IBM Canada", "ibm", "ibm.com", "careers.ibm.com", "", "", ""),
        ("Accenture Canada", "accenture", "accenture.com", "careers.accenture.com", "", "", ""),
        ("Deloitte Canada", "deloitte", "deloitte.ca", "careers.deloitte.ca", "", "", ""),
        ("PwC Canada", "pwc|pricewaterhousecoopers", "pwc.com", "jobs.pwc.com", "", "", ""),
        ("KPMG Canada", "kpmg", "kpmg.ca", "careers.kpmg.ca", "", "", ""),
        ("EY Canada", "ernst young|ey", "ey.com", "careers.ey.com", "", "", ""),
        ("CGI Canada", "cgi", "cgi.com", "jobs.cgi.com", "", "", ""),
        ("Infosys Canada", "infosys", "infosys.com", "careers.infosys.com", "", "", ""),
        ("Tata Consultancy Services Canada", "tcs canada|tata consultancy services|tcs", "tcs.com", "careers.tcs.com", "", "", ""),
        ("Capgemini Canada", "capgemini", "capgemini.com", "jobs.capgemini.com", "", "", ""),
        ("Fujitsu Canada", "fujitsu", "fujitsu.com", "fujitsu.com", "", "", ""),
        ("Siemens Canada", "siemens", "siemens.com", "jobs.siemens.com", "", "", ""),
        ("Bosch Canada", "bosch", "bosch.com", "jobs.bosch.com", "", "", ""),
        ("3M Canada", "3m", "3m.com", "3m.com", "", "", ""),
        ("GE Canada", "general electric|ge", "ge.com", "jobs.ge.com", "", "", ""),
        ("PepsiCo Canada", "pepsico|pepsi", "pepsico.com", "pepsicojobs.com", "", "", ""),
        ("Coca-Cola Canada", "coca cola|cocacola", "coca-cola.com", "careers.coca-colacompany.com", "", "", ""),
        ("Nestlé Canada", "nestle", "nestle.ca", "careers.nestle.ca", "", "", ""),
        ("Unilever Canada", "unilever", "unilever.com", "careers.unilever.com", "", "", ""),
        ("Procter & Gamble Canada", "procter and gamble|p&g|pg canada", "pg.com", "pgcareers.com", "", "", ""),
        ("Johnson & Johnson Canada", "johnson and johnson|jnj|j&j", "jnj.com", "jobs.jnj.com", "", "", ""),
        ("Pfizer Canada", "pfizer", "pfizer.ca", "pfizer.com", "", "", ""),
        ("Moderna Canada", "moderna", "modernatx.com", "modernatx.com", "", "", ""),
        ("GSK Canada", "glaxosmithkline|gsk", "gsk.com", "jobs.gsk.com", "", "", ""),
        ("Novartis Canada", "novartis", "novartis.com", "novartis.com", "", "", ""),
        ("Roche Canada", "roche", "rochecanada.com", "careers.roche.com", "", "", ""),
        ("Medtronic Canada", "medtronic", "medtronic.com", "jobs.medtronic.com", "", "", ""),
        ("Bayer Canada", "bayer", "bayer.ca", "career.bayer.com", "", "", ""),
        ("Air Transat", "transat", "airtransat.com", "airtransat.com", "", "", ""),
        ("Porter Airlines", "porter", "flyporter.com", "flyporter.com", "", "", ""),
        ("Canada Post", "postes canada", "canadapost-postescanada.ca", "canadapost-postescanada.ca", "", "", ""),
        ("Purolator", "", "purolator.com", "purolator.com", "", "", ""),
        ("FedEx Canada", "fedex", "fedex.com", "careers.fedex.com", "", "", ""),
        ("UPS Canada", "ups", "ups.com", "jobs.ups.com", "", "", ""),
        ("Royal Canadian Mint", "monnaie royale canadienne", "mint.ca", "mint.ca", "", "", ""),
        ("Canadian Broadcasting Corporation", "cbc|radio-canada|radio canada", "cbc.ca", "cbc.radio-canada.ca", "", "", ""),
        ("Global News", "globalnews|global television", "globalnews.ca", "globalnews.ca", "", "", ""),
        ("CTV", "ctv news|bell media", "ctv.ca", "ctv.ca", "", "", ""),
        ("Telefilm Canada", "telefilm", "telefilm.ca", "telefilm.ca", "", "", ""),
    ),
    "Belgique": _rows(
        ("Proximus", "", "proximus.be", "jobs.proximus.be", "", "", ""),
        ("BNP Paribas Fortis", "bnp paribas fortis|fortis", "bnpparibasfortis.be", "jobs.bnpparibasfortis.com", "", "", ""),
        ("KBC Group", "kbc", "kbc.com", "jobs.kbc.com", "", "", ""),
        ("UCB", "ucb pharma", "ucb.com", "careers.ucb.com", "", "", ""),
        ("Solvay", "", "solvay.com", "careers.solvay.com", "", "", ""),
        ("Umicore", "", "umicore.com", "jobs.umicore.com", "", "", ""),
        ("Colruyt Group", "colruyt", "colruytgroup.com", "jobs.colruytgroup.com", "", "", ""),
        ("Delhaize", "ahold delhaize", "delhaize.be", "careers.aholddelhaize.com", "", "", ""),
        ("Telenet", "", "telenet.be", "jobs.telenet.be", "", "", ""),
        ("Bpost", "bpost group", "bpost.be", "jobs.bpost.be", "", "", ""),
    ),
    "Suisse": _rows(
        ("Nestlé", "nestle", "nestle.com", "careers.nestle.com", "", "", ""),
        ("Novartis", "", "novartis.com", "www.novartis.com", "", "", ""),
        ("Roche", "", "roche.com", "careers.roche.com", "", "", ""),
        ("UBS", "ubs group", "ubs.com", "jobs.ubs.com", "", "", ""),
        ("Credit Suisse", "credit suisse|ubs credit suisse", "credit-suisse.com", "jobs.credit-suisse.com", "", "", ""),
        ("Swisscom", "", "swisscom.ch", "jobs.swisscom.ch", "", "", ""),
        ("Logitech", "", "logitech.com", "careers.logitech.com", "", "", ""),
        ("Zurich Insurance Group", "zurich insurance|zurich", "zurich.com", "careers.zurich.com", "", "", ""),
        ("Swiss Re", "swissre", "swissre.com", "careers.swissre.com", "", "", ""),
        ("Migros", "migros suisse", "migros.ch", "jobs.migros.ch", "", "", ""),
    ),
    "Etats-Unis": _rows(
        ("Apple", "", "apple.com", "jobs.apple.com", "", "", ""),
        ("Microsoft", "", "microsoft.com", "careers.microsoft.com", "", "", ""),
        ("Google", "alphabet|google alphabet", "google.com", "careers.google.com", "", "", ""),
        ("Amazon", "", "amazon.com", "amazon.jobs", "", "", ""),
        ("Meta Platforms", "meta|facebook", "meta.com", "metacareers.com", "", "", ""),
        ("Tesla", "", "tesla.com", "www.tesla.com", "", "", ""),
        ("IBM", "", "ibm.com", "careers.ibm.com", "", "", ""),
        ("Oracle", "", "oracle.com", "www.oracle.com", "", "", ""),
        ("JPMorgan Chase", "jpmorgan|jp morgan|chase", "jpmorganchase.com", "careers.jpmorgan.com", "", "", ""),
        ("Bank of America", "bofa", "bankofamerica.com", "careers.bankofamerica.com", "", "", ""),
    ),
    "Royaume-Uni": _rows(
        ("HSBC", "", "hsbc.com", "jobs.hsbc.com", "", "", ""),
        ("Barclays", "", "barclays.com", "jobs.barclays.com", "", "", ""),
        ("Lloyds Banking Group", "lloyds bank|lloyds", "lloydsbankinggroup.com", "www.lloydsbankinggroup.com", "", "", ""),
        ("BP", "british petroleum", "bp.com", "jobs.bp.com", "", "", ""),
        ("Shell UK", "shell", "shell.com", "jobs.shell.com", "", "", ""),
        ("Tesco", "", "tesco.com", "www.tesco-careers.com", "", "", ""),
        ("Vodafone", "", "vodafone.com", "careers.vodafone.com", "", "", ""),
        ("BT Group", "bt", "bt.com", "jobs.bt.com", "", "", ""),
        ("Rolls-Royce", "rolls royce", "rolls-royce.com", "careers.rolls-royce.com", "", "", ""),
        ("BAE Systems", "bae", "baesystems.com", "jobs.baesystems.com", "", "", ""),
    ),
    "Allemagne": _rows(
        ("Siemens", "", "siemens.com", "jobs.siemens.com", "", "", ""),
        ("Volkswagen", "vw", "volkswagen.com", "www.volkswagen-group.com", "", "", ""),
        ("BMW", "bmw group", "bmw.com", "www.bmwgroup.jobs", "", "", ""),
        ("Mercedes-Benz Group", "mercedes-benz|mercedes|daimler", "mercedes-benz.com", "group.mercedes-benz.com", "", "", ""),
        ("Deutsche Bank", "", "db.com", "careers.db.com", "", "", ""),
        ("SAP", "", "sap.com", "jobs.sap.com", "", "", ""),
        ("Allianz", "", "allianz.com", "careers.allianz.com", "", "", ""),
        ("BASF", "", "basf.com", "www.basf.com", "", "", ""),
        ("Deutsche Telekom", "telekom", "telekom.com", "www.telekom.com", "", "", ""),
        ("Lufthansa", "lufthansa group", "lufthansa.com", "be-lufthansa.com", "", "", ""),
    ),
    "Espagne": _rows(
        ("Banco Santander", "santander", "santander.com", "www.santander.com", "", "", ""),
        ("BBVA", "", "bbva.com", "careers.bbva.com", "", "", ""),
        ("Telefónica", "telefonica", "telefonica.com", "www.telefonica.com", "", "", ""),
        ("Inditex", "zara|zara inditex", "inditex.com", "www.inditex.com", "", "", ""),
        ("Iberdrola", "", "iberdrola.com", "www.iberdrola.com", "", "", ""),
        ("Repsol", "", "repsol.com", "www.repsol.com", "", "", ""),
        ("CaixaBank", "caixabank", "caixabank.com", "www.caixabank.com", "", "", ""),
        ("Mapfre", "", "mapfre.com", "www.mapfre.com", "", "", ""),
        ("Ferrovial", "", "ferrovial.com", "www.ferrovial.com", "", "", ""),
        ("ACS Group", "acs", "grupoacs.com", "www.grupoacs.com", "", "", ""),
    ),
    "Italie": _rows(
        ("Enel", "", "enel.com", "www.enel.com", "", "", ""),
        ("Eni", "", "eni.com", "www.eni.com", "", "", ""),
        ("Intesa Sanpaolo", "intesa", "intesasanpaolo.com", "www.intesasanpaolo.com", "", "", ""),
        ("UniCredit", "unicredit", "unicreditgroup.eu", "www.unicreditgroup.eu", "", "", ""),
        ("Stellantis Italy", "stellantis italia|fiat|alfa romeo", "stellantis.com", "careers.stellantis.com", "", "", ""),
        ("Leonardo", "leonardo spa", "leonardo.com", "www.leonardo.com", "", "", ""),
        ("Telecom Italia", "tim|telecom italia", "gruppotim.it", "www.gruppotim.it", "", "", ""),
        ("Generali", "assicurazioni generali", "generali.com", "www.generali.com", "", "", ""),
        ("Pirelli", "", "pirelli.com", "www.pirelli.com", "", "", ""),
        ("Luxottica", "essilorluxottica", "essilorluxottica.com", "www.essilorluxottica.com", "", "", ""),
    ),
    "Portugal": _rows(
        ("EDP", "energias de portugal", "edp.com", "www.edp.com", "", "", ""),
        ("Galp Energia", "galp", "galp.com", "www.galp.com", "", "", ""),
        ("Millennium BCP", "bcp|millennium bcp", "millenniumbcp.pt", "ind.millenniumbcp.pt", "", "", ""),
        ("NOS", "nos portugal", "nos.pt", "www.nos.pt", "", "", ""),
        ("Sonae", "", "sonae.pt", "www.sonae.pt", "", "", ""),
        ("Jerónimo Martins", "jeronimo martins", "jeronimomartins.com", "www.jeronimomartins.com", "", "", ""),
        ("Caixa Geral de Depósitos", "cgd|caixa geral", "cgd.pt", "www.cgd.pt", "", "", ""),
        ("REN", "redes energeticas nacionais", "ren.pt", "www.ren.pt", "", "", ""),
        ("CTT", "ctt correios", "ctt.pt", "www.ctt.pt", "", "", ""),
        ("The Navigator Company", "navigator", "thenavigatorcompany.com", "www.thenavigatorcompany.com", "", "", ""),
    ),
    "Pays-Bas": _rows(
        ("ING Group", "ing", "ing.com", "www.ing.jobs", "", "", ""),
        ("Rabobank", "", "rabobank.com", "www.rabobank.com", "", "", ""),
        ("ABN AMRO", "abn amro", "abnamro.com", "www.abnamro.com", "", "", ""),
        ("Philips", "", "philips.com", "www.philips.com", "", "", ""),
        ("ASML", "", "asml.com", "www.asml.com", "", "", ""),
        ("Heineken", "", "theheinekencompany.com", "careers.heineken.com", "", "", ""),
        ("Unilever", "", "unilever.com", "careers.unilever.com", "", "", ""),
        ("Shell Netherlands", "shell nederland|shell", "shell.com", "jobs.shell.com", "", "", ""),
        ("KLM", "klm royal dutch airlines", "klm.com", "careers.klm.com", "", "", ""),
        ("Booking.com", "booking", "booking.com", "careers.booking.com", "bookingcom", "", ""),
    ),
    "Suede": _rows(
        ("Volvo Group", "volvo", "volvogroup.com", "www.volvogroup.com", "", "", ""),
        ("Ericsson", "", "ericsson.com", "www.ericsson.com", "", "", ""),
        ("IKEA", "", "ikea.com", "www.ikea.com", "", "", ""),
        ("H&M", "hennes and mauritz|hm", "hm.com", "career.hm.com", "", "", ""),
        ("Spotify", "", "spotify.com", "www.lifeatspotify.com", "spotify", "", ""),
        ("Atlas Copco", "", "atlascopco.com", "www.atlascopco.com", "", "", ""),
        ("Electrolux", "", "electroluxgroup.com", "www.electroluxgroup.com", "", "", ""),
        ("Skanska", "", "skanska.com", "www.skanska.com", "", "", ""),
        ("SEB", "skandinaviska enskilda banken", "sebgroup.com", "sebgroup.com", "", "", ""),
        ("Swedbank", "", "swedbank.com", "www.swedbank.com", "", "", ""),
    ),
    "Norvege": _rows(
        ("Equinor", "", "equinor.com", "www.equinor.com", "", "", ""),
        ("Telenor", "", "telenor.com", "www.telenor.com", "", "", ""),
        ("DNB", "dnb bank", "dnb.no", "www.dnb.no", "", "", ""),
        ("Norsk Hydro", "hydro", "hydro.com", "www.hydro.com", "", "", ""),
        ("Yara International", "yara", "yara.com", "www.yara.com", "", "", ""),
        ("Orkla", "", "orkla.com", "www.orkla.com", "", "", ""),
        ("Gjensidige", "", "gjensidige.com", "www.gjensidige.com", "", "", ""),
        ("Storebrand", "", "storebrand.no", "www.storebrand.no", "", "", ""),
        ("Aker Solutions", "aker", "akersolutions.com", "www.akersolutions.com", "", "", ""),
        ("Norwegian Air Shuttle", "norwegian", "norwegian.com", "www.norwegian.com", "", "", ""),
    ),
    "Danemark": _rows(
        ("Maersk", "a.p. moller maersk|ap moller maersk", "maersk.com", "www.maersk.com", "", "", ""),
        ("Novo Nordisk", "", "novonordisk.com", "www.novonordisk.com", "", "", ""),
        ("Carlsberg", "", "carlsberggroup.com", "www.carlsberggroup.com", "", "", ""),
        ("Danske Bank", "", "danskebank.com", "danskebank.com", "", "", ""),
        ("Vestas", "", "vestas.com", "www.vestas.com", "", "", ""),
        ("LEGO Group", "lego", "lego.com", "www.lego.com", "", "", ""),
        ("Nordea Denmark", "nordea", "nordea.com", "www.nordea.com", "", "", ""),
        ("Jyske Bank", "", "jyskebank.com", "www.jyskebank.com", "", "", ""),
        ("Coloplast", "", "coloplast.com", "www.coloplast.com", "", "", ""),
        ("GN Store Nord", "gn|gn audio", "gn.com", "www.gn.com", "", "", ""),
    ),
    "Finlande": _rows(
        ("Nokia", "", "nokia.com", "www.nokia.com", "", "", ""),
        ("KONE", "", "kone.com", "www.kone.com", "", "", ""),
        ("Fortum", "", "fortum.com", "www.fortum.com", "", "", ""),
        ("UPM-Kymmene", "upm", "upm.com", "www.upm.com", "", "", ""),
        ("Stora Enso", "", "storaenso.com", "www.storaenso.com", "", "", ""),
        ("Wärtsilä", "wartsila", "wartsila.com", "www.wartsila.com", "", "", ""),
        ("Neste", "", "neste.com", "www.neste.com", "", "", ""),
        ("Sampo", "", "sampo.com", "www.sampo.com", "", "", ""),
        ("Metso", "", "metso.com", "www.metso.com", "", "", ""),
        ("Elisa", "elisa finland", "elisa.com", "elisa.com", "", "", ""),
    ),
    "Australie": _rows(
        ("BHP", "", "bhp.com", "www.bhp.com", "", "", ""),
        ("Rio Tinto Australia", "rio tinto", "riotinto.com", "www.riotinto.com", "", "", ""),
        ("Commonwealth Bank", "cba|commbank", "commbank.com.au", "www.commbank.com.au", "", "", ""),
        ("Westpac", "", "westpac.com.au", "www.westpac.com.au", "", "", ""),
        ("ANZ", "australia and new zealand banking", "anz.com", "www.anz.com", "", "", ""),
        ("National Australia Bank", "nab", "nab.com.au", "www.nab.com.au", "", "", ""),
        ("Telstra", "", "telstra.com.au", "careers.telstra.com", "", "", ""),
        ("Qantas", "", "qantas.com", "www.qantas.com", "", "", ""),
        ("Woolworths Group", "woolworths", "woolworthsgroup.com.au", "www.woolworthsgroup.com.au", "", "", ""),
        ("Coles Group", "coles", "colesgroup.com.au", "www.colesgroup.com.au", "", "", ""),
    ),
    "Nouvelle-Zelande": _rows(
        ("Fonterra", "", "fonterra.com", "www.fonterra.com", "", "", ""),
        ("Air New Zealand", "air nz", "airnewzealand.com", "www.airnewzealand.com", "", "", ""),
        ("Spark New Zealand", "spark", "spark.co.nz", "www.spark.co.nz", "", "", ""),
        ("ANZ New Zealand", "anz nz", "anz.co.nz", "www.anz.co.nz", "", "", ""),
        ("Westpac New Zealand", "westpac nz", "westpac.co.nz", "www.westpac.co.nz", "", "", ""),
        ("The Warehouse Group", "warehouse group", "thewarehousegroup.co.nz", "www.thewarehouse.co.nz", "", "", ""),
        ("Fletcher Building", "fletcher", "fletcherbuilding.com", "fletcherbuilding.com", "", "", ""),
        ("Meridian Energy", "meridian", "meridianenergy.co.nz", "www.meridianenergy.co.nz", "", "", ""),
        ("Contact Energy", "contact", "contact.co.nz", "contact.co.nz", "", "", ""),
        ("Z Energy", "", "z.co.nz", "z.co.nz", "", "", ""),
    ),
    "Maroc": _rows(
        ("OCP Group", "ocp", "ocpgroup.ma", "www.ocpgroup.ma", "", "", ""),
        ("Maroc Telecom", "iam|ittissalat al-maghrib", "iam.ma", "www.iam.ma", "", "", ""),
        ("Attijariwafa Bank", "attijariwafa", "attijariwafabank.com", "www.attijariwafabank.com", "", "", ""),
        ("Banque Populaire", "groupe banque populaire|bcp maroc", "gbp.ma", "www.gbp.ma", "", "", ""),
        ("BMCE Bank of Africa", "bank of africa|bmce", "bankofafrica.ma", "www.bankofafrica.ma", "", "", ""),
        ("CIH Bank", "cih", "cihbank.ma", "www.cihbank.ma", "", "", ""),
        ("Royal Air Maroc", "ram", "royalairmaroc.com", "www.royalairmaroc.com", "", "", ""),
        ("Managem", "", "managemgroup.com", "www.managemgroup.com", "", "", ""),
        ("Lesieur Cristal", "lesieur", "lesieurcristal.ma", "www.lesieurcristal.ma", "", "", ""),
        ("Centrale Danone Maroc", "centrale danone", "centraledanone.ma", "www.centraledanone.ma", "", "", ""),
    ),
    "Cote d Ivoire": _rows(
        ("Orange Côte d’Ivoire", "orange cote d ivoire|orange ci", "orange.ci", "www.orange.ci", "", "", ""),
        ("MTN Côte d’Ivoire", "mtn cote d ivoire|mtn ci", "mtn.ci", "www.mtn.ci", "", "", ""),
        ("Moov Africa Côte d’Ivoire", "moov cote d ivoire|moov ci", "moov-africa.ci", "www.moov-africa.ci", "", "", ""),
        ("Société Générale Côte d’Ivoire", "sgci|societe generale cote d ivoire", "societegenerale.ci", "www.societegenerale.ci", "", "", ""),
        ("NSIA Banque", "nsia", "nsiabanque.com", "www.nsiabanque.com", "", "", ""),
        ("Ecobank Côte d’Ivoire", "ecobank cote d ivoire|ecobank ci", "ecobank.com", "www.ecobank.com", "", "", ""),
        ("SIB", "societe ivoirienne de banque", "sib.ci", "www.sib.ci", "", "", ""),
        ("CIE", "compagnie ivoirienne d electricite", "cie.ci", "www.cie.ci", "", "", ""),
        ("SODECI", "", "sodeci.ci", "www.sodeci.ci", "", "", ""),
        ("Petroci", "", "petroci.ci", "www.petroci.ci", "", "", ""),
    ),
    "Senegal": _rows(
        ("Sonatel", "", "sonatel.sn", "www.sonatel.sn", "", "", ""),
        ("Free Sénégal", "free senegal|promobile", "free.sn", "www.free.sn", "", "", ""),
        ("Expresso Sénégal", "expresso senegal", "expresso.sn", "www.expresso.sn", "", "", ""),
        ("Société Générale Sénégal", "sgbs|societe generale senegal", "societegenerale.sn", "www.societegenerale.sn", "", "", ""),
        ("BNP Paribas Sénégal", "bici senegal|bnp paribas senegal", "bnpparibas.sn", "www.bnpparibas.sn", "", "", ""),
        ("Ecobank Sénégal", "ecobank senegal", "ecobank.com", "www.ecobank.com", "", "", ""),
        ("La Poste Sénégal", "poste senegal", "laposte.sn", "www.laposte.sn", "", "", ""),
        ("Senelec", "", "senelec.sn", "www.senelec.sn", "", "", ""),
        ("CFAO Sénégal", "cfao senegal", "cfaogroup.com", "www.cfaogroup.com", "", "", ""),
        ("TotalEnergies Sénégal", "totalenergies senegal", "totalenergies.sn", "totalenergies.com", "", "", ""),
    ),
    "Cameroun": _rows(
        ("Orange Cameroun", "orange cameroon", "orange.cm", "www.orange.cm", "", "", ""),
        ("MTN Cameroun", "mtn cameroon", "mtn.cm", "www.mtn.cm", "", "", ""),
        ("Nexttel", "nexttel cameroun", "nexttel.cm", "www.nexttel.cm", "", "", ""),
        ("Société Générale Cameroun", "sgbc|societe generale cameroun", "societegenerale.cm", "www.societegenerale.cm", "", "", ""),
        ("Afriland First Bank", "afriland", "afrilandfirstbank.com", "www.afrilandfirstbank.com", "", "", ""),
        ("Ecobank Cameroun", "ecobank cameroon", "ecobank.com", "www.ecobank.com", "", "", ""),
        ("Camtel", "", "camtel.cm", "www.camtel.cm", "", "", ""),
        ("CIMENCAM", "", "cimencam.cm", "www.cimencam.cm", "", "", ""),
        ("Dangote Cement Cameroun", "dangote cameroun", "dangote.com", "www.dangote.com", "", "", ""),
        ("Les Brasseries du Cameroun", "sabc|brasseries du cameroun", "lesbrasseriesducameroun.com", "www.lesbrasseriesducameroun.com", "", "", ""),
    ),
    "Kenya": _rows(
        ("Safaricom", "", "safaricom.co.ke", "www.safaricom.co.ke", "", "", ""),
        ("Kenya Commercial Bank", "kcb|kcb group", "kcbgroup.com", "www.kcbgroup.com", "", "", ""),
        ("Equity Bank", "equity group", "equitygroupholdings.com", "equitygroupholdings.com", "", "", ""),
        ("Co-operative Bank of Kenya", "co-operative bank|coop bank kenya", "co-opbank.co.ke", "www.co-opbank.co.ke", "", "", ""),
        ("Kenya Airways", "kq", "kenya-airways.com", "www.kenya-airways.com", "", "", ""),
        ("East African Breweries", "eabl", "eabl.com", "www.eabl.com", "", "", ""),
        ("Nation Media Group", "nation media", "nationmedia.com", "www.nationmedia.com", "", "", ""),
        ("KenGen", "kenya electricity generating", "kengen.co.ke", "www.kengen.co.ke", "", "", ""),
        ("Kenya Power", "kplc", "kplc.co.ke", "www.kplc.co.ke", "", "", ""),
        ("I&M Bank", "i and m bank kenya", "imbank.com", "www.imbank.com", "", "", ""),
    ),
    "Nigeria": _rows(
        ("MTN Nigeria", "mtn ng", "mtn.ng", "www.mtn.ng", "", "", ""),
        ("Airtel Nigeria", "airtel ng", "airtel.com.ng", "www.airtel.com.ng", "", "", ""),
        ("Globacom", "glo", "gloworld.com", "www.gloworld.com", "", "", ""),
        ("Access Bank", "access holdings", "accessbankplc.com", "www.accessbankplc.com", "", "", ""),
        ("Zenith Bank", "", "zenithbank.com", "www.zenithbank.com", "", "", ""),
        ("Guaranty Trust Holding Company", "gtco|gtbank|guaranty trust", "gtcoplc.com", "www.gtcoplc.com", "", "", ""),
        ("First Bank of Nigeria", "firstbank|first bank", "firstbanknigeria.com", "www.firstbanknigeria.com", "", "", ""),
        ("United Bank for Africa", "uba", "ubagroup.com", "www.ubagroup.com", "", "", ""),
        ("Dangote Group", "dangote", "dangote.com", "www.dangote.com", "", "", ""),
        ("Nigerian Breweries", "nb plc", "nbplc.com", "www.nbplc.com", "", "", ""),
    ),
    "Ghana": _rows(
        ("MTN Ghana", "", "mtn.com.gh", "www.mtn.com.gh", "", "", ""),
        ("Vodafone Ghana", "telecel ghana|vodafone gh", "vodafone.com.gh", "www.vodafone.com.gh", "", "", ""),
        ("AirtelTigo", "airteltigo", "airteltigo.com.gh", "www.airteltigo.com.gh", "", "", ""),
        ("GCB Bank", "gcb", "gcbbank.com.gh", "www.gcbbank.com.gh", "", "", ""),
        ("Ecobank Ghana", "", "ecobank.com", "www.ecobank.com", "", "", ""),
        ("Absa Bank Ghana", "absa ghana", "absa.com.gh", "www.absa.com.gh", "", "", ""),
        ("CalBank", "cal bank", "calbank.net", "www.calbank.net", "", "", ""),
        ("GNPC", "ghana national petroleum corporation", "gnpcghana.com", "www.gnpcghana.com", "", "", ""),
        ("Volta River Authority", "vra", "vra.com", "www.vra.com", "", "", ""),
        ("Ghana Ports and Harbours Authority", "gpha", "ghanaports.gov.gh", "www.ghanaports.gov.gh", "", "", ""),
    ),
    "Afrique du Sud": _rows(
        ("Sasol", "", "sasol.com", "www.sasol.com", "", "", ""),
        ("Standard Bank", "standard bank group", "standardbank.com", "www.standardbank.com", "", "", ""),
        ("FirstRand", "fnb|firstrand", "firstrand.co.za", "www.firstrand.co.za", "", "", ""),
        ("Absa Group", "absa", "absa.africa", "www.absa.africa", "", "", ""),
        ("Nedbank", "", "nedbank.co.za", "www.nedbank.co.za", "", "", ""),
        ("MTN South Africa", "mtn za", "mtn.co.za", "www.mtn.co.za", "", "", ""),
        ("Vodacom", "", "vodacom.com", "www.vodacom.com", "", "", ""),
        ("Shoprite", "shoprite holdings", "shopriteholdings.co.za", "www.shopriteholdings.co.za", "", "", ""),
        ("Pick n Pay", "pick n pay stores", "pnp.co.za", "www.pnp.co.za", "", "", ""),
        ("Bidvest Group", "bidvest", "bidvest.com", "www.bidvest.com", "", "", ""),
    ),
    "Tunisie": _rows(
        ("Tunisie Telecom", "", "tunisietelecom.tn", "www.tunisietelecom.tn", "", "", ""),
        ("Ooredoo Tunisie", "ooredoo tn", "ooredoo.tn", "www.ooredoo.tn", "", "", ""),
        ("Orange Tunisie", "orange tn", "orange.tn", "www.orange.tn", "", "", ""),
        ("BIAT", "banque internationale arabe de tunisie", "biat.com.tn", "www.biat.com.tn", "", "", ""),
        ("Amen Bank", "", "amenbank.com.tn", "www.amenbank.com.tn", "", "", ""),
        ("Banque de Tunisie", "bt", "bt.com.tn", "www.bt.com.tn", "", "", ""),
        ("STEG", "societe tunisienne de electricite et du gaz", "steg.com.tn", "www.steg.com.tn", "", "", ""),
        ("STIS", "societe tunisienne de l industrie du sucre", "stis.com.tn", "www.stis.com.tn", "", "", ""),
        ("One Tech Holding", "one tech", "onetech-group.com", "www.onetech-group.com", "", "", ""),
        ("Poulina Group Holding", "poulina", "poulinagroupholding.com", "www.poulinagroupholding.com", "", "", ""),
    ),
    "Algerie": _rows(
        ("Sonatrach", "", "sonatrach.dz", "sonatrach.com", "", "", ""),
        ("Djezzy", "", "djezzy.dz", "www.djezzy.dz", "", "", ""),
        ("Mobilis", "atm mobilis", "mobilis.dz", "www.mobilis.dz", "", "", ""),
        ("Ooredoo Algérie", "ooredoo algerie|nedjma", "ooredoo.dz", "www.ooredoo.dz", "", "", ""),
        ("Banque Nationale d’Algérie", "bna", "bna.dz", "www.bna.dz", "", "", ""),
        ("Crédit Populaire d’Algérie", "cpa algerie", "cpa-bank.dz", "www.cpa-bank.dz", "", "", ""),
        ("Cevital", "", "cevital.com", "www.cevital.com", "", "", ""),
        ("Naftal", "", "naftal.dz", "www.naftal.dz", "", "", ""),
        ("Air Algérie", "air algerie", "airalgerie.dz", "www.airalgerie.dz", "", "", ""),
        ("Algérie Télécom", "algerie telecom", "algerietelecom.dz", "www.algerietelecom.dz", "", "", ""),
    ),
    "Egypte": _rows(
        ("Telecom Egypt", "we egypt", "te.eg", "www.te.eg", "", "", ""),
        ("Vodafone Egypt", "vodafone eg", "vodafone.com.eg", "web.vodafone.com.eg", "", "", ""),
        ("Orange Egypt", "orange eg", "orange.eg", "www.orange.eg", "", "", ""),
        ("Etisalat Misr", "etisalat egypt|e& egypt", "etisalat.eg", "www.etisalat.eg", "", "", ""),
        ("Commercial International Bank", "cib egypt", "cibeg.com", "www.cibeg.com", "", "", ""),
        ("Banque Misr", "", "banquemisr.com", "www.banquemisr.com", "", "", ""),
        ("National Bank of Egypt", "nbe", "nbe.com.eg", "www.nbe.com.eg", "", "", ""),
        ("Orascom Construction", "orascom", "orascom.com", "www.orascom.com", "", "", ""),
        ("Elsewedy Electric", "elsewedy", "elsewedyelectric.com", "www.elsewedyelectric.com", "", "", ""),
        ("EgyptAir", "egypt air", "egyptair.com", "www.egyptair.com", "", "", ""),
    ),
    "Rwanda": _rows(
        ("MTN Rwanda", "", "mtn.co.rw", "www.mtn.co.rw", "", "", ""),
        ("Airtel Rwanda", "", "airtel.co.rw", "www.airtel.co.rw", "", "", ""),
        ("Bank of Kigali", "bk", "bk.rw", "www.bk.rw", "", "", ""),
        ("I&M Bank Rwanda", "i and m bank rwanda", "imbank.com", "www.imbank.com", "", "", ""),
        ("Cogebanque", "", "cogebanque.co.rw", "www.cogebanque.co.rw", "", "", ""),
        ("BRD", "rwanda development bank", "brd.rw", "www.brd.rw", "", "", ""),
        ("Rwanda Energy Group", "reg", "reg.rw", "www.reg.rw", "", "", ""),
        ("RURA", "rwanda utilities regulatory authority", "rura.rw", "www.rura.rw", "", "", ""),
        ("RwandAir", "", "rwandair.com", "www.rwandair.com", "", "", ""),
        ("Crystal Ventures", "crystal ventures ltd", "cvt.rw", "www.cvt.rw", "", "", ""),
    ),
}
