[theme]
primaryColor = "#7c3aed"
backgroundColor = "#f5f3ff"
secondaryBackgroundColor = "#ffffff"
textColor = "#312e81"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
headless = true
