[theme]
primaryColor = "#0E7490"
backgroundColor = "#F4F1EA"
secondaryBackgroundColor = "#ffffff"
textColor = "#0B1220"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false

[client]
showSidebarNavigation = false
